Deplagiator/Controllers/ReferencesController.cs
using BL.Validation.Functions;
using Deplagiator.Models;
using Deplagiator.Validation.Structures;
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Configuration;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Xml.Serialization;
using Deplagiator.Helpers;
using System.Data.Entity;

namespace Deplagiator.Controllers
{
    [Authorize]
    public class ReferencesController : Controller
    {
        private string referenceDocumentsFolderPath = HostingEnvironment.MapPath(WebConfigurationManager.AppSettings["referenceDocumentsPath"]);
        private string jobInfoFileName = WebConfigurationManager.AppSettings["checkJobInfoFileName"];

        private ApplicationDbContext context = new ApplicationDbContext();
        private Validator validator = new Validator();

        // GET: References
        public ActionResult Index()
        {
            List<Author> authors = context.Authors.ToList();

            return View(authors);
        }

        public ActionResult Upload()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Upload(UploadViewModel model, HttpPostedFileBase document)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    ValidationResult result = validator.UploadReference(model.FirstName, model.LastName, document);

                    if (result)
                    {
                        SaveUpload(model, document);
                        return RedirectToAction("Index");
                    }

                    ControllerExtensions.AddValidationErrors(result, this);
                }
                catch (Exception e)
                {
                    return ControllerExtensions.RedirectToError(this, e);
                }
            }
            return View(model);
        }

        private void SaveUpload(UploadViewModel model, HttpPostedFileBase document)
        {
            using (DbContextTransaction t = context.Database.BeginTransaction())
            {

                try
                {
                    Author existingAuthor = context.Authors.FirstOrDefault(x => x.FirstName == model.FirstName && x.LastName == x.LastName);

                    if (existingAuthor == null)
                    {
                        context.Authors.Add(new Author() { FirstName = model.FirstName, LastName = model.LastName });
                    }
                    context.SaveChanges();

                    int authorId = context.Authors.Single(x => x.FirstName == model.FirstName && x.LastName == model.LastName).Id;

                    byte[] fileBuffer;
                    using (BinaryReader br = new BinaryReader(document.InputStream))
                    {
                        fileBuffer = br.ReadBytes((int)document.InputStream.Length);
                    }

                    context.ReferenceDocuments.Add(new ReferenceDocument()
                    {
                        AuthorId = authorId,
                        UploadDate = DateTime.Now,
                        DocumentBytes = fileBuffer,
                        DocumentType = document.ContentType,
                        DocumentName = Path.GetFileName(document.FileName)
                    });

                    context.SaveChanges();
                    t.Commit();
                }
                catch (Exception e)
                {
                    t.Rollback();
                    throw e;
                }
            }
            /*string guid = Guid.NewGuid().ToString();
            string path = Path.Combine(referenceDocumentsFolderPath, model.FirstName + "_" + model.LastName); 
            // Create a folder for the author if it doesn't exist
            if (!Directory.Exists(path))
            {
                Directory.CreateDirectory(path);
            }

            // Create a new directory with the GUID in the name
            path = Path.Combine(path, guid);
            Directory.CreateDirectory(path);

            // Create an AuthorUpload object to be serialized into the XML information file
            AuthorUpload information = new AuthorUpload
            {
                UploadedDocument = new UploadedDocument
                {
                    FileName = Path.GetFileName(document.FileName),
                    UploadedDate = DateTime.Now
                },
                Author = new Author 
                {
                    FirstName = model.FirstName,
                    LastName = model.LastName
                },
                GUID = guid
            };
            
            // Serialize the information object and save it
            XmlSerializer serializer = new XmlSerializer(typeof(AuthorUpload));
            using (StreamWriter sw = new StreamWriter(Path.Combine(path, jobInfoFileName)))
            {
                serializer.Serialize(sw, information);    
            }

            // Save the document in the new directory
            document.SaveAs(Path.Combine(path, Path.GetFileName(document.FileName)));*/
        }
        
        public ActionResult ByAuthor(int authorId)
        {
            try
            {
                List<ReferenceDocument> documents = FindDocumentsByAuthor(authorId);
                ViewBag.Author = context.Authors.Single(x => x.Id == authorId);

                return View(documents);
            }
            catch (Exception e)
            {
                TempData.Add("ex", e);
                return Redirect(WebConfigurationManager.AppSettings["genericErrorUrl"]);
            }

        }

        private List<ReferenceDocument> FindDocumentsByAuthor(int authorId)
        {
            return context.ReferenceDocuments.Where(x => x.AuthorId == authorId).ToList();
        }

        public ActionResult Read(int documentId)
        {
            try
            {
                ReferenceDocument document = context.ReferenceDocuments.Single(x => x.Id == documentId);
                return File(document.DocumentBytes, document.DocumentType);
            }
            catch (Exception e)
            {
                TempData.Add("ex", e);
                return Redirect(WebConfigurationManager.AppSettings["genericErrorUrl"]);
            }

        }

    }

}

Deplagiator/Views/References/ByAuthor.cshtml
@model List<ReferenceDocument>
@{
    ViewBag.Title = "Documents from " + ViewBag.Author.FirstName + " " + ViewBag.Author.LastName;
}

<link href="~/Content/TotalTable.css" rel="stylesheet" />
<h2>@ViewBag.Title</h2>

<div class="table-responsive">
    <table class="table table-hover total-table">
        <thead>
            <tr>
                <th>Document name</th>
                <th>Upload date</th>
                <th></th>
            </tr>
            <tr class="filters-row"></tr>
        </thead>
        <tbody>
            @foreach (ReferenceDocument obj in Model)
            {
                var authorName = ViewBag.Author.FirstName + "_" + ViewBag.Author.LastName;
                <tr>
                    <td>@obj.DocumentName</td>
                    <td>@obj.UploadDate</td>
                    <td><a href="/References/Read?documentId=@obj.Id" class="btn btn-xs btn-link"><span class="glyphicon glyphicon-chevron-right"></span></a></td>
                </tr>
            }
        </tbody>
    </table>
</div>

<script src="~/Scripts/TotalTable.js"></script>
<script>
    initializeFiltering(3, [
        { index: 0, styleClassNames: ['table-search-md'], cellClassNames: ['table-search-align-left'] },
        { index: 1, styleClassNames: ['table-search-md'], cellClassNames: ['table-search-align-left'] }
    ]);
</script>

Deplagiator/Views/References/Index.cshtml
@model List<Author>
@{
    ViewBag.Title = "Index";
}
<link href="~/Content/TotalTable.css" rel="stylesheet" />
<h2>Existing authors</h2>

<div class="table-responsive">
    <table class="table table-hover total-table">
        <thead>
            <tr>
                <th>First name</th>
                <th>Last name</th>
                <th></th>
            </tr>
            <tr class="filters-row"></tr>
        </thead>
        <tbody>
            @for (int i = 0; i < Model.Count; i++)
            {
                <tr>
                    <td>@Model[i].FirstName</td>
                    <td>@Model[i].LastName</td>
                    <td><a href="/References/ByAuthor?authorId=@Model[i].Id" class="btn btn-info btn-xs"><span class="glyphicon glyphicon-search"></span></a></td>
                </tr>
            }
        </tbody>
    </table>
</div>

<script src="~/Scripts/TotalTable.js"></script>
<script>
    initializeFiltering(3, [
        { index: 0, styleClassNames: ['table-search-md'], cellClassNames: ['table-search-align-left'] },
        { index: 1, styleClassNames: ['table-search-md'], cellClassNames: ['table-search-align-left'] }
    ]);
</script>

Deplagiator/Views/References/Upload.cshtml
@model Deplagiator.Models.UploadViewModel

@{
    ViewBag.Title = "Upload";
}

<style>
    input[type="file"]{
        margin-top:8px;
    }
</style>

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Upload", "References", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h3>Author information</h3>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <h3>Select document</h3>
        <hr />

        <div class="form-group">
            <label class="control-label col-md-2">File:</label>
            <div class="col-md-10">
                <input type="file" name="document" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Upload" class="btn btn-default" />
            </div>
        </div>

    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>